package enums;

public enum Controllers
{
	ADICIONAR_PRODUTO, CADASTRAR_NOVA_CAFETERIA, CADASTRAR_NOVO_FUNCIONARIO, CADASTRO_CHOOSE, CADASTRO_CLIENTE, CADASTRO_FUNCIONARIO, CADASTRO_PRIMEIRA_CAFETERIA, GERENTE_PRINCIPAL_OPCOES, CLIENTE_OPCOES, COMUM_OPCOES, DEMITIR_FUNCIONARIO, EMITIR_ALERTA, FAZER_PEDIDO,FUNCIONARIO_OPCOES, GERENTE_OPCOES, LOGIN_FIRST, MODIFICAR_FUNCIONARIO, MUDAR_NOME, MUDAR_SENHA, MUDAR_SEU_SALARIO, MUDAR_TELEFONE, ROOT_LAYOUT, VER_ALERTAS, VER_CAFETERIAS, VER_CARDAPIO, VER_FREQUENCIA, VER_FUNCIONARIOS, VER_HISTORICO, VER_NOTA_FISCAL, VER_NOTAS,VER_PRODUTOS, VER_SEU_SALARIO, VER_SEU_TELEFONE, VER_VENDAS;
}